# Generated by Django 5.0 on 2025-01-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
