# Generated by Django 5.1.5 on 2025-01-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_signature',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
